map_type: costmap

obstacle_range: 0.5
raytrace_range: 0.5

transform_tolerance: 0.7

inflation_radius: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
